### ISSUE TITLE
Vaporの標準AuthenticationにBasic認証とBearer認証しかなかった件

### ISSUE THREAD

**Issue by lemo-nade-room** [CreideaNITNC/TutHub#9]
ユーザーIDとパスワード直送りで認証するBasic認証と、検証後にトークン引渡しで認証するAPI専用みたいなBearer認証しか無かった。自前で実装することも考えたけど、そもそもDigest認証がそんなにBasic認証に劣ってるかっていうのは思う。

[Basic認証/Digest認証](https://twitter.com/ockeghem/status/1261087572849131520?s=20&t=gM2K4Xbx6cS4IP5n2ABPFA)

Basic認証で行くか、どうせ自作するならSHA256かSHA512で（最近のRFCではSHA256とSHA512がDigest認証に追加されてるらしい。ブラウザでは使えんけど）やってもいいなぁとも思う。やりたければBcrypt付きBasic認証とかもできるけど

どう思う？ 俺はBasicでいいと思います。TutHubはTLS完備だし

**Comment by Takechan-0** [comment]
TLSが破られない限りBasic認証かDigest認証かの違いは現れないから，Basic認証でいこう。
